# Site settings
title: SLF-YYQ
email: gaohaoyang126@126.com
description: YYQ的博客 WEB全栈追随者
# > # this means to ignore newlines until "baseurl:"
#   Write an awesome description for your new site here. You can edit this
#   line in _config.yml. It will appear in your document head meta (for
#   Google search results) and in your feed.xml site description.

# baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://blog.thankbabe.com" # the base hostname & protocol for your site
# twitter_username: jekyllrb
github_username:  sflaqiu
permalink: /:year/:month/:day/:title/

# Build settings
markdown: kramdown
gems: [jekyll-paginate]

paginate: 10
paginate_path: "page:num"

# highlight
# 本地用rouge, github上用pygments
# highlighter: pygments
# highlighter: rouge
# highlighter: false
